#!/usr/bin/env bash

RBENV_VERSION="v0.4.0"
RBENV_DIR="${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.rbenv"
RBENV_GIT_URL="https://github.com/sstephenson/rbenv.git"

echo "Running build script..."

# Install or update RBENV
if [ -d $RBENV_DIR ]; then
    echo "RBENV has already been installed. Updating it..."
    cd $RBENV_DIR
    git pull master
    git checkout $RBENV_VERSION
else
    echo "Installing RBENV..."
    git clone $RBENV_GIT_URL $RBENV_DIR
    cd $RBENV_DIR
    git checkout $RBENV_VERSION
fi


source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/configenv
