#!/usr/bin/env bash

RBENV_VERSION="master"
RBENV_DIR="${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.rbenv"
RBENV_GIT_URL="https://github.com/sstephenson/rbenv.git"

RUBYBUILD_GIT_URL="https://github.com/sstephenson/ruby-build.git"
RUBYBUILD_VERSION="master"
RUBYBUILD_DIR="$RBENV_DIR/plugins/ruby-build"

echo "Running build script..."

# Install or update RBENV
if [ -d $RBENV_DIR ]; then
    echo "RBENV has already been installed. Updating it..."
    cd $RBENV_DIR
    git pull origin $RBENV_VERSION
    git checkout $RBENV_VERSION
else
    echo "Installing RBENV..."
    git clone $RBENV_GIT_URL $RBENV_DIR
    cd $RBENV_DIR
    git checkout $RBENV_VERSION
fi

# Install or update ruby-build
if [ -d $RUBYBUILD_DIR ]; then
    echo "ruby-build has already been installed. Updating it..."
    cd $RUBYBUILD_DIR
    git pull origin $RUBYBUILD_VERSION
    git checkout $RUBYBUILD_VERSION
else
    echo "Installing ruby-build"
    git clone $RUBYBUILD_GIT_URL $RUBYBUILD_DIR
    cd $RUBYBUILD_DIR
    git checkout $RUBYBUILD_VERSION
fi

source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/configenv

mkdir -p $RBENV_ROOT/cache

# Necessary because of compile bug in Ruby on Fedora / Redhat for Ruby 1.9.3.
# FIXME: This probably won't work with later versions of Ruby.
# https://github.com/sstephenson/ruby-build/wiki#make-error-for-200-p247-and-lower-on-fedorared-hat
# https://bugs.ruby-lang.org/issues/8384
# https://bugs.ruby-lang.org/projects/ruby-193/repository/revisions/43486

curl -fsSL https://bugs.ruby-lang.org/projects/ruby-193/repository/revisions/43486/diff?format=diff | rbenv install --patch `cat $OPENSHIFT_REPO_DIR/.ruby-version`


# rbenv install -v `cat $OPENSHIFT_REPO_DIR/.ruby-version`
