#!/bin/bash
# The logic to start up your application should be put in this

source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/configenv
echo "Current ruby version: `ruby --version`"


echo "Starting Unicorn..."
ruby `gem which unicorn` -c ${OPENSHIFT_REPO_DIR}unicorn.rb -E production -D
