#!/bin/bash

set -e

UNICORN_DIR="${OPENSHIFT_DATA_DIR}/unicorn/"



source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/configenv
echo "Current Ruby version: `ruby --version`"

echo "Stopping Unicorn..."
cat "${UNICORN_DIR}pids/unicorn.pid" | xargs kill -QUIT
rm -rf "${UNICORN_DIR}sockets/unicorn.socket"
rm -rf "${UNICORN_DIR}pids/unicorn.pid"

echo "Stopping nginx..."
${OPENSHIFT_REPO_DIR}nginx.startscript stop
