#!/bin/bash


UNICORN_DIR="${OPENSHIFT_DATA_DIR}/unicorn/"
UPIDFILE="${UNICORN_DIR}pids/unicorn.pid"


source ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/configenv

echo "Stopping Unicorn..."
if [ -e $UPIDFILE ]; then
    cat "$UPIDFILE" | xargs kill -QUIT
fi

rm -rf "${UNICORN_DIR}sockets/unicorn.socket"
rm -rf "${UNICORN_DIR}pids/unicorn.pid"

/bin/sh ${OPENSHIFT_REPO_DIR}nginx.startscript stop
